[package]
name = "xsynth-clib"
version = "0.1.0"
edition = "2021"

[lib]
name = "xsynth"
crate-type = ["cdylib"]

[dependencies]
xsynth-core = "0.1.0"
xsynth-realtime = "0.1.0"
xsynth-soundfonts = "0.1.0"

[build-dependencies]
cbindgen = "0.26.0"
version-number = "0.4.0"
